services:
  gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

  typesense:
    image: typesense/typesense:27.0
    container_name: typesense
    ports:
      - "8080:8080"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors=true'
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEYS=${GEMINI_API_KEYS}
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}

      - TYPESENSE_HOST=${TYPESENSE_HOST}
      - TYPESENSE_PORT=${TYPESENSE_PORT}
      - TYPESENSE_PROTOCOL=${TYPESENSE_PROTOCOL}
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    networks:
      - app-network
    depends_on:
      - redis
      - db
      - typesense
    volumes:
      - uploads_data:/usr/src/app/uploads

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  db:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
  uploads_data: