@host = http://localhost
@baseUrl = {{host}}/api/v1

###
# @name registerCompanyReq
POST {{baseUrl}}/auth/company/register
Content-Type: application/json

{
  "name": "Tech Corp",
  "industry": "IT",
  "size": "51-200",
  "contactName": "John Doe",
  "email": "company@techcorp.com",
  "password": "Password123!"
}

###
# @name loginCompanyReq
POST {{baseUrl}}/auth/company/login
Content-Type: application/json

{
  "email": "company@techcorp.com",
  "password": "Password123!"
}

###
@companyToken = {{loginCompanyReq.response.body.accessToken}}

###
GET {{baseUrl}}/auth/me
Authorization: Bearer {{companyToken}}

###
@inviteToken = 74f817d8b0c446aa738fbcedc601c292199888ea101c202da6558ec9e890e805

###
# @name registerEmployeeReq
POST {{baseUrl}}/auth/employee/register
Content-Type: application/json

{
  "token": "{{inviteToken}}",
  "password": "Password123!",
  "gender": "female",
  "hobbies": "Читання, Подорожі",
  "favoriteAnimal": "Кіт"
}

###
# @name loginEmployeeReq
POST {{baseUrl}}/auth/employee/login
Content-Type: application/json

{
  "email": "employee@techcorp.com",
  "password": "Password123!"
}

###
@employeeToken = {{loginEmployeeReq.response.body.accessToken}}

###
GET {{baseUrl}}/auth/me
Authorization: Bearer {{employeeToken}}

###
POST {{baseUrl}}/auth/google/mobile
Content-Type: application/json

{
  "idToken": "GOOGLE_ID_TOKEN"
}

###
GET {{baseUrl}}/auth/google