@host = http://localhost
@baseUrl = {{host}}/api/v1

# отриманий токен при реєстрації
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbXBhbnlAdGVjaGNvcnAuY29tIiwiaWQiOiI2OWFiMjA0ODczYjVhOGZjMmIyZmIzYWQiLCJ1c2VyVHlwZSI6ImNvbXBhbnkiLCJpYXQiOjE3NzI4MjI2MzIsImV4cCI6MTc3MzQyNzQzMn0.1YKpAscRwsbbGZnSZengvDD2qZJ2M1UTpyeiVDCVcQo
# отриманий id при реєстрації
@companyId = 69ab204873b5a8fc2b2fb3ad

###
GET {{baseUrl}}/companies
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}

###
PATCH {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Tech Corp Updated",
  "size": "200-500"
}

###
DELETE {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}

###
# @name inviteEmployeeReq
POST {{baseUrl}}/companies/invite-employee
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "employee@techcorp.com"
}