@host = http://localhost
@baseUrl = {{host}}/api/v1

# токен компанії
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbXBhbnlAdGVjaGNvcnAuY29tIiwiaWQiOiI2OWFlY2Q5ZTcwZmFlNDJmYTNhZTNiOTMiLCJ1c2VyVHlwZSI6ImNvbXBhbnkiLCJpYXQiOjE3NzMwNjM1ODIsImV4cCI6MTc3MzY2ODM4Mn0.kDW0Fqm9Vi2HPS32RpWeK0TGGRTWII1lgP5yxlQIKyY
# айді компанії
@companyId = 69aecd9e70fae42fa3ae3b93

###
# @name inviteEmployeeReq
POST {{baseUrl}}/companies/invite-employee
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "employee@techcorp.com",
  "name": "Jane Smith",
  "department": "Engineering",
  "role": "middle"
}

### 
GET {{baseUrl}}/companies
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}

###
PATCH {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Tech Corp Updated",
  "size": "200-500"
}

###
GET {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}

###
DELETE {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}

# --------------------------------------------------

###
GET {{baseUrl}}/companies/me/departments
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/companies/me/departments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Engineering"
}

###
POST {{baseUrl}}/companies/me/departments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Engineering"
}

###
# @name inviteEmployeeReq
POST {{baseUrl}}/companies/invite-employee
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "employee@techcorp.com",
  "name": "Jane Smith",
  "department": "Engineering",
  "role": "middle"
}

###
POST {{baseUrl}}/companies/invite-employee
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "employee2@techcorp.com",
  "name": "John Doe",
  "department": "NonExistentDepartment",
  "role": "junior"
}

### 
GET {{baseUrl}}/companies
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}

###
PATCH {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Tech Corp Updated",
  "size": "200-500"
}

###
GET {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}

###
DELETE {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}